### ISSUE TITLE
CHEMBL moves under permanent embargo

### ISSUE THREAD

**Issue by lilleswing** [mahendra-awale/medchem_moves#1]
https://figshare.com/articles/dataset/chemblDB3_sqlitdb/12912080

Hi the ChEMBL moves are under permanent embargo on figshare.  Is there another place we can get them from?

**Comment by mahendra-awale** [comment]
Hi, thank you for pointing this out. I changed the file permission. You can now download the database with same figshare link.

**Comment by lilleswing** [comment]
Thanks @mahendra-awale !
